### ISSUE TITLE
pcmanfm-qt FTBFS 

### ISSUE THREAD

**Issue by luis-pereira** [lxqt/lxqt#1501]
##### Expected Behavior
Build

##### Current Behavior
```
[61/119] Building CXX object pcmanfm-qt/pcmanfm/CMakeFiles/pcmanfm-qt.dir/tabpage.cpp.o
FAILED: pcmanfm-qt/pcmanfm/CMakeFiles/pcmanfm-qt.dir/tabpage.cpp.o 
/usr/lib/ccache/bin/clang++  -DLIBFM_DATA_DIR=\"/share/libfm\" -DLXQT_DATA_DIR=\"/usr/share\" -DLXQT_ETC_XDG_DIR=\"/etc/xdg\" -DLXQT_GRAPHICS_DIR=\"/usr/share/lxqt/graphics\" -DLXQT_RELATIVE_SHARE_DIR=\"lxqt\" -DLXQT_RELATIVE_SHARE_TRANSLATIONS_DIR=\"lxqt/translations\" -DLXQT_SHARE_DIR=\"/usr/share/lxqt\" -DLXQT_SHARE_TRANSLATIONS_DIR=\"/usr/share/lxqt/translations\" -DPCMANFM_DATA_DIR=\"/usr/share/pcmanfm-qt\" -DPCMANFM_QT_VERSION=\"0.13.0\" -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NO_FOREACH -DQT_NO_KEYWORDS -DQT_STRICT_ITERATORS -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -Ipcmanfm-qt/pcmanfm -I/run/media/lpereira/d87b7441-31f4-4616-86df-12de7d3145b2/home/lpereira/lxqt/lxqt/pcmanfm-qt/pcmanfm -Ipcmanfm-qt/pcmanfm/pcmanfm-qt_autogen/include -I/usr/include/qt/QtGui/5.11.0 -I/usr/include/qt/QtGui/5.11.0/QtGui -I/usr/include/qt/QtCore/5.11.0 -I/usr/include/qt/QtCore/5.11.0/QtCore -isystem /usr/include/qt -isystem /usr/include/qt/QtX11Extras -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++ -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtDBus -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/menu-cache -Ilibfm-qt/src/CMakeFiles/include -fno-exceptions -Wall -Wextra -Wchar-subscripts -Wno-long-long -Wpointer-arith -Wundef -Wformat-security -Wnon-virtual-dtor -Woverloaded-virtual -Wpedantic -Wno-gnu-zero-variadic-macro-arguments -std=c++11 -fdiagnostics-color=always -g -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -std=gnu++11 -MD -MT pcmanfm-qt/pcmanfm/CMakeFiles/pcmanfm-qt.dir/tabpage.cpp.o -MF pcmanfm-qt/pcmanfm/CMakeFiles/pcmanfm-qt.dir/tabpage.cpp.o.d -o pcmanfm-qt/pcmanfm/CMakeFiles/pcmanfm-qt.dir/tabpage.cpp.o -c /run/media/lpereira/d87b7441-31f4-4616-86df-12de7d3145b2/home/lpereira/lxqt/lxqt/pcmanfm-qt/pcmanfm/tabpage.cpp
/run/media/lpereira/d87b7441-31f4-4616-86df-12de7d3145b2/home/lpereira/lxqt/lxqt/pcmanfm-qt/pcmanfm/tabpage.cpp:79:18: error: no member named 'setShadowHidden' in 'PCManFM::View'                                                              
    folderView_->setShadowHidden(settings.shadowHidden());
    ~~~~~~~~~~~  ^
1 error generated.                                                                                                      
[63/119] Building CXX object pcmanfm-qt/pcmanfm/CMakeFiles/pcmanfm-qt.dir/desktopwindow.cpp.o
FAILED: pcmanfm-qt/pcmanfm/CMakeFiles/pcmanfm-qt.dir/desktopwindow.cpp.o 
/usr/lib/ccache/bin/clang++  -DLIBFM_DATA_DIR=\"/share/libfm\" -DLXQT_DATA_DIR=\"/usr/share\" -DLXQT_ETC_XDG_DIR=\"/etc/xdg\" -DLXQT_GRAPHICS_DIR=\"/usr/share/lxqt/graphics\" -DLXQT_RELATIVE_SHARE_DIR=\"lxqt\" -DLXQT_RELATIVE_SHARE_TRANSLATIONS_DIR=\"lxqt/translations\" -DLXQT_SHARE_DIR=\"/usr/share/lxqt\" -DLXQT_SHARE_TRANSLATIONS_DIR=\"/usr/share/lxqt/translations\" -DPCMANFM_DATA_DIR=\"/usr/share/pcmanfm-qt\" -DPCMANFM_QT_VERSION=\"0.13.0\" -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NO_FOREACH -DQT_NO_KEYWORDS -DQT_STRICT_ITERATORS -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -Ipcmanfm-qt/pcmanfm -I/run/media/lpereira/d87b7441-31f4-4616-86df-12de7d3145b2/home/lpereira/lxqt/lxqt/pcmanfm-qt/pcmanfm -Ipcmanfm-qt/pcmanfm/pcmanfm-qt_autogen/include -I/usr/include/qt/QtGui/5.11.0 -I/usr/include/qt/QtGui/5.11.0/QtGui -I/usr/include/qt/QtCore/5.11.0 -I/usr/include/qt/QtCore/5.11.0/QtCore -isystem /usr/include/qt -isystem /usr/include/qt/QtX11Extras -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++ -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtDBus -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/menu-cache -Ilibfm-qt/src/CMakeFiles/include -fno-exceptions -Wall -Wextra -Wchar-subscripts -Wno-long-long -Wpointer-arith -Wundef -Wformat-security -Wnon-virtual-dtor -Woverloaded-virtual -Wpedantic -Wno-gnu-zero-variadic-macro-arguments -std=c++11 -fdiagnostics-color=always -g -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -std=gnu++11 -MD -MT pcmanfm-qt/pcmanfm/CMakeFiles/pcmanfm-qt.dir/desktopwindow.cpp.o -MF pcmanfm-qt/pcmanfm/CMakeFiles/pcmanfm-qt.dir/desktopwindow.cpp.o.d -o pcmanfm-qt/pcmanfm/CMakeFiles/pcmanfm-qt.dir/desktopwindow.cpp.o -c /run/media/lpereira/d87b7441-31f4-4616-86df-12de7d3145b2/home/lpereira/lxqt/lxqt/pcmanfm-qt/pcmanfm/desktopwindow.cpp
/run/media/lpereira/d87b7441-31f4-4616-86df-12de7d3145b2/home/lpereira/lxqt/lxqt/pcmanfm-qt/pcmanfm/desktopwindow.cpp:111:9: error: use of undeclared identifier 'setShadowHidden'
        setShadowHidden(settings.shadowHidden());
        ^
1 error generated.                                             
```
##### System Information

* Distribution & Version: not relevant
* Kernel: not relevant 
* Qt Version: 5.11
* liblxqt Version: not relevant
* Package version: git

**Comment by tsujan** [comment]
Your libfm-qt installation isn't up-to-date.

**Comment by agaida** [comment]
ok - build fine with Qt 5.10 both i386 and amd64 - https://gist.github.com/agaida/98167a2f99c45deb87fb1e6b06d2fa82

**Comment by tsujan** [comment]
Builds fine with Qt 5.11 too.

**Comment by luis-pereira** [comment]
I did update libfm-qt. I started using ccache to speed up builds. Can be a ccache mess up.
@tsujan @agaida It's most certainly something in my configuration. Debugging it.

**Comment by luis-pereira** [comment]
ccache was the culprit. Must keep that in mind.
