### ISSUE TITLE
lxqt-config Qt4 FTBFS

### ISSUE THREAD

**Issue by luis-pereira** [lxqt/lxqt#293]
```
FAILED: /usr/bin/clang++   -DLXQT_ETC_XDG_DIR=\"/etc/xdg\" -DLXQT_SHARE_DIR=\"/usr/share/lxqt\" -DLXQT_VERSION=\"0.7.0\" -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_MIMETYPES -DQT_XML_LIB -g -fPIE -Isrc -I../src -isystem /usr/include/qt4 -isystem /usr/include/qt4/QtGui -isystem /usr/include/qt4/QtDBus -isystem /usr/include/qt4/QtCore -I/usr/include/lxqt -isystem /usr/include/qt4/QtXml -I/usr/include/qtxdg -I/usr/include/QtMimeTypes -I../src/qcategorizedview -MMD -MT src/CMakeFiles/lxqt-config.dir/mainwindow.cpp.o -MF src/CMakeFiles/lxqt-config.dir/mainwindow.cpp.o.d -o src/CMakeFiles/lxqt-config.dir/mainwindow.cpp.o -c ../src/mainwindow.cpp
../src/mainwindow.cpp:221:34: error: no member named 'ThemeChange' in 'QEvent'; did you mean 'ThreadChange'?
    if (event->type() == QEvent::ThemeChange)
                         ~~~~~~~~^~~~~~~~~~~
                                 ThreadChange
/usr/include/qt4/QtCore/qcoreevent.h:95:9: note: 'ThreadChange' declared here
        ThreadChange = 22,                      // object has changed threads
        ^
1 error generated.
ninja: build stopped: subcommand failed.
```

@paulolieuthier The offending commit is yours lxqt-config@8c82d65ac8982ae189c85367cd65bd58fae886c9 Can you take a look ? Assigning to you.
